[package]
name = "raytrace"
version = "0.1.0"
authors = ["Danil Ineev"]
edition = "2021"

[dependencies]
png = "0.14.0"
rand = "0.6.4"
threadpool = "1.7.1"
num_cpus = "1.9.0"
json = "0.11.13"
egui = "0.24.1"
eframe = "0.24.1"
egui_extras = "0.24.2"
rfd = "0.12.1"
